# Generated by Django 3.1.3 on 2022-02-16 07:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('toilet', '0003_alter_comment_id_bookmarks'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookmarks',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
